import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import {
  Award,
  Copy,
  Download,
  QrCode,
  RotateCcw,
  ShieldOff,
  Trash2,
  UserCheck,
} from "lucide-react";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

import { CertificateStatusBadge } from "@/components/dashboard/StatusBadge";
import { CertificateQrPreview } from "@/components/admin/CertificateQrPreview";
import { getAllEventsAdmin } from "@/services/events";
import { getAttendanceCodes } from "@/services/attendance";
import {
  buildVerificationUrl,
  certificatesToCSV,
  deleteCertificate,
  getAllCertificatesAdmin,
  issueCertificate,
  issueCertificatesBulk,
  setCertificateStatus,
  type CertificateInput,
} from "@/services/certificates";
import { formatEventDate, formatEventDay } from "@/lib/dates";
import { downloadQrSvg } from "@/lib/qr";
import type { Certificate } from "@/types";

const EMPTY_FORM = {
  recipient_name: "",
  recipient_email: "",
  certificate_type: "Certificate of Participation",
  organizer_name: "",
  organizer_organization: "Unstop Igniters Club",
  signer_name: "",
  signer_designation: "",
  signer_signature_url: "",
  certificate_file_url: "",
  issue_date: "",
};

function downloadTextFile(content: string, fileName: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  try {
    const link = document.createElement("a");
    link.href = url;
    link.download = fileName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  } finally {
    URL.revokeObjectURL(url);
  }
}

/**
 * Admin certificate tools.
 *
 * Issues certificates for an event, revokes or deletes them, and produces the
 * QR code that goes onto the printed certificate. The certificate number and
 * verification token are generated by the database, so nothing identifying is
 * chosen here.
 */
export function CertificatesPanel({ createdBy }: { createdBy: string | null }) {
  const queryClient = useQueryClient();
  const [eventId, setEventId] = useState("");
  const [form, setForm] = useState(EMPTY_FORM);
  const [qrTarget, setQrTarget] = useState<Certificate | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<Certificate | null>(null);

  const { data: events } = useQuery({ queryKey: ["events-admin"], queryFn: getAllEventsAdmin });

  const {
    data: certificates,
    isLoading,
    isError,
  } = useQuery({
    queryKey: ["certificates-admin", eventId],
    queryFn: () => getAllCertificatesAdmin(eventId || undefined),
    enabled: Boolean(eventId),
  });

  const selectedEvent = useMemo(
    () => events?.find((event) => event.id === eventId) ?? null,
    [events, eventId]
  );

  const invalidate = () => {
    void queryClient.invalidateQueries({ queryKey: ["certificates-admin", eventId] });
  };

  const sharedInput = (): Omit<CertificateInput, "recipient_name" | "recipient_email"> => ({
    event_id: eventId,
    certificate_type: form.certificate_type,
    organizer_name: form.organizer_name,
    organizer_organization: form.organizer_organization,
    signer_name: form.signer_name,
    signer_designation: form.signer_designation,
    signer_signature_url: form.signer_signature_url,
    certificate_file_url: form.certificate_file_url,
    issue_date: form.issue_date || null,
  });

  const issueOne = useMutation({
    mutationFn: () => {
      if (!eventId) throw new Error("Select an event first.");
      if (!form.recipient_name.trim()) throw new Error("Enter the recipient's name.");
      return issueCertificate(
        {
          ...sharedInput(),
          recipient_name: form.recipient_name,
          recipient_email: form.recipient_email,
        },
        createdBy
      );
    },
    onSuccess: (certificate) => {
      toast.success(`Issued ${certificate.certificateNumber}`);
      setForm((current) => ({ ...current, recipient_name: "", recipient_email: "" }));
      setQrTarget(certificate);
      invalidate();
    },
    onError: (error: unknown) =>
      toast.error(error instanceof Error ? error.message : "Failed to issue the certificate."),
  });

  const issueForAttendees = useMutation({
    mutationFn: async () => {
      if (!eventId) throw new Error("Select an event first.");
      const codes = await getAttendanceCodes(eventId);
      const attendees = codes
        .filter((code) => code.status === "used" && code.participantName)
        .map((code) => ({
          name: code.participantName as string,
          email: code.participantEmail ?? null,
        }));

      if (attendees.length === 0) {
        throw new Error("No recorded attendees for this event yet.");
      }

      return issueCertificatesBulk(attendees, sharedInput(), createdBy);
    },
    onSuccess: ({ issued, skipped }) => {
      if (issued.length === 0) {
        toast.info(`Nothing to issue — ${skipped} attendee(s) already have a certificate.`);
      } else {
        toast.success(
          `Issued ${issued.length} certificate(s)${skipped ? `, skipped ${skipped} already issued` : ""}.`
        );
      }
      invalidate();
    },
    onError: (error: unknown) =>
      toast.error(error instanceof Error ? error.message : "Failed to issue certificates."),
  });

  const changeStatus = useMutation({
    mutationFn: ({ id, status }: { id: string; status: "issued" | "revoked" }) =>
      setCertificateStatus(id, status),
    onSuccess: (_data, variables) => {
      toast.success(variables.status === "revoked" ? "Certificate revoked." : "Certificate restored.");
      invalidate();
    },
    onError: () => toast.error("Failed to update the certificate."),
  });

  const removeCertificate = useMutation({
    mutationFn: (id: string) => deleteCertificate(id),
    onSuccess: () => {
      toast.success("Certificate deleted.");
      setDeleteTarget(null);
      invalidate();
    },
    onError: () => toast.error("Failed to delete the certificate."),
  });

  const copyLink = async (certificate: Certificate) => {
    try {
      await navigator.clipboard.writeText(buildVerificationUrl(certificate.verificationToken));
      toast.success("Verification link copied.");
    } catch {
      toast.error("Could not copy the verification link.");
    }
  };

  const exportCsv = () => {
    if (!certificates?.length) return;
    const slug = (selectedEvent?.title ?? "event")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "");
    downloadTextFile(certificatesToCSV(certificates), `certificates-${slug}.csv`, "text/csv");
  };

  const stats = useMemo(() => {
    const list = certificates ?? [];
    return {
      total: list.length,
      valid: list.filter((certificate) => certificate.status === "issued").length,
      revoked: list.filter((certificate) => certificate.status === "revoked").length,
    };
  }, [certificates]);

  const updateForm = (key: keyof typeof EMPTY_FORM, value: string) =>
    setForm((current) => ({ ...current, [key]: value }));

  return (
    <div className="space-y-6">
      {/* Event picker */}
      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-base">Select event</CardTitle>
          <CardDescription>
            Certificates are always tied to an event, so the event name, date and day on the
            certificate stay in sync with the event record.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          <Select value={eventId} onValueChange={setEventId}>
            <SelectTrigger className="max-w-xl">
              <SelectValue placeholder="Choose an event" />
            </SelectTrigger>
            <SelectContent>
              {events?.map((event) => (
                <SelectItem key={event.id} value={event.id}>
                  {event.title}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>

          {selectedEvent && (
            <p className="text-sm text-muted-foreground">
              {formatEventDate(selectedEvent.eventDate)} ·{" "}
              {formatEventDay(selectedEvent.eventDate)}
              {selectedEvent.venue ? ` · ${selectedEvent.venue}` : ""}
            </p>
          )}
        </CardContent>
      </Card>

      {eventId && (
        <>
          {/* Issue form */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base">Issue certificate</CardTitle>
              <CardDescription>
                The certificate ID and verification token are generated by the database.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid gap-4 md:grid-cols-2">
                <div>
                  <Label htmlFor="cert-recipient">Recipient name</Label>
                  <Input
                    id="cert-recipient"
                    value={form.recipient_name}
                    onChange={(event) => updateForm("recipient_name", event.target.value)}
                    placeholder="Full name as printed"
                  />
                </div>
                <div>
                  <Label htmlFor="cert-email">Recipient email</Label>
                  <Input
                    id="cert-email"
                    type="email"
                    value={form.recipient_email}
                    onChange={(event) => updateForm("recipient_email", event.target.value)}
                    placeholder="Links the certificate to their account"
                  />
                </div>
                <div>
                  <Label htmlFor="cert-type">Certificate type</Label>
                  <Input
                    id="cert-type"
                    value={form.certificate_type}
                    onChange={(event) => updateForm("certificate_type", event.target.value)}
                  />
                </div>
                <div>
                  <Label htmlFor="cert-issue-date">Issue date</Label>
                  <Input
                    id="cert-issue-date"
                    type="date"
                    value={form.issue_date}
                    onChange={(event) => updateForm("issue_date", event.target.value)}
                  />
                </div>
                <div>
                  <Label htmlFor="cert-organizer">Organiser name</Label>
                  <Input
                    id="cert-organizer"
                    value={form.organizer_name}
                    onChange={(event) => updateForm("organizer_name", event.target.value)}
                    placeholder="e.g. UIC Core Team"
                  />
                </div>
                <div>
                  <Label htmlFor="cert-organization">Organised by</Label>
                  <Input
                    id="cert-organization"
                    value={form.organizer_organization}
                    onChange={(event) => updateForm("organizer_organization", event.target.value)}
                  />
                </div>
                <div>
                  <Label htmlFor="cert-signer">Signatory name</Label>
                  <Input
                    id="cert-signer"
                    value={form.signer_name}
                    onChange={(event) => updateForm("signer_name", event.target.value)}
                  />
                </div>
                <div>
                  <Label htmlFor="cert-designation">Signatory designation</Label>
                  <Input
                    id="cert-designation"
                    value={form.signer_designation}
                    onChange={(event) => updateForm("signer_designation", event.target.value)}
                    placeholder="e.g. Faculty Coordinator"
                  />
                </div>
                <div>
                  <Label htmlFor="cert-signature">Signature image URL</Label>
                  <Input
                    id="cert-signature"
                    value={form.signer_signature_url}
                    onChange={(event) => updateForm("signer_signature_url", event.target.value)}
                    placeholder="Optional"
                  />
                </div>
                <div>
                  <Label htmlFor="cert-file">Certificate file URL</Label>
                  <Input
                    id="cert-file"
                    value={form.certificate_file_url}
                    onChange={(event) => updateForm("certificate_file_url", event.target.value)}
                    placeholder="Optional — enables View / Download"
                  />
                </div>
              </div>

              <div className="flex flex-wrap gap-2">
                <Button
                  className="gap-2 bg-gradient-to-r from-primary to-secondary"
                  onClick={() => issueOne.mutate()}
                  disabled={issueOne.isPending}
                >
                  <Award className="h-4 w-4" aria-hidden />
                  {issueOne.isPending ? "Issuing…" : "Issue certificate"}
                </Button>

                <Button
                  variant="outline"
                  className="gap-2"
                  onClick={() => issueForAttendees.mutate()}
                  disabled={issueForAttendees.isPending}
                >
                  <UserCheck className="h-4 w-4" aria-hidden />
                  {issueForAttendees.isPending
                    ? "Issuing…"
                    : "Issue for all recorded attendees"}
                </Button>
              </div>
              <p className="text-xs text-muted-foreground">
                Bulk issuing uses the attendees who redeemed an attendance code for this event and
                skips anyone who already has a certificate.
              </p>
            </CardContent>
          </Card>

          {/* Issued list */}
          <Card>
            <CardHeader className="pb-3">
              <div className="flex flex-wrap items-start justify-between gap-3">
                <div>
                  <CardTitle className="text-base">Issued certificates</CardTitle>
                  <CardDescription>
                    {stats.total} total · {stats.valid} valid · {stats.revoked} revoked
                  </CardDescription>
                </div>
                <Button
                  variant="outline"
                  size="sm"
                  className="gap-2"
                  onClick={exportCsv}
                  disabled={!certificates?.length}
                >
                  <Download className="h-4 w-4" aria-hidden />
                  Export CSV
                </Button>
              </div>
            </CardHeader>
            <CardContent>
              {isLoading ? (
                <p className="py-6 text-center text-sm text-muted-foreground">
                  Loading certificates…
                </p>
              ) : isError ? (
                <p className="py-6 text-center text-sm text-destructive">
                  Could not load certificates for this event.
                </p>
              ) : !certificates?.length ? (
                <p className="py-6 text-center text-sm text-muted-foreground">
                  No certificates issued for this event yet.
                </p>
              ) : (
                <div className="overflow-x-auto">
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Certificate ID</TableHead>
                        <TableHead>Recipient</TableHead>
                        <TableHead className="hidden md:table-cell">Email</TableHead>
                        <TableHead className="hidden lg:table-cell">Issued</TableHead>
                        <TableHead>Status</TableHead>
                        <TableHead className="text-right">Actions</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {certificates.map((certificate) => (
                        <TableRow key={certificate.id}>
                          <TableCell className="font-mono text-xs">
                            {certificate.certificateNumber}
                          </TableCell>
                          <TableCell className="font-medium">
                            {certificate.recipientName}
                          </TableCell>
                          <TableCell className="hidden md:table-cell text-sm text-muted-foreground">
                            {certificate.recipientEmail ?? "—"}
                          </TableCell>
                          <TableCell className="hidden lg:table-cell text-sm text-muted-foreground">
                            {formatEventDate(certificate.issueDate)}
                          </TableCell>
                          <TableCell>
                            <CertificateStatusBadge status={certificate.status} />
                          </TableCell>
                          <TableCell>
                            <div className="flex justify-end gap-1">
                              <Button
                                variant="ghost"
                                size="icon"
                                className="h-8 w-8"
                                onClick={() => setQrTarget(certificate)}
                                aria-label={`Show QR code for ${certificate.certificateNumber}`}
                              >
                                <QrCode className="h-4 w-4" aria-hidden />
                              </Button>
                              <Button
                                variant="ghost"
                                size="icon"
                                className="h-8 w-8"
                                onClick={() => void copyLink(certificate)}
                                aria-label={`Copy verification link for ${certificate.certificateNumber}`}
                              >
                                <Copy className="h-4 w-4" aria-hidden />
                              </Button>
                              {certificate.status === "issued" ? (
                                <Button
                                  variant="ghost"
                                  size="icon"
                                  className="h-8 w-8 text-warning"
                                  onClick={() =>
                                    changeStatus.mutate({ id: certificate.id, status: "revoked" })
                                  }
                                  aria-label={`Revoke ${certificate.certificateNumber}`}
                                >
                                  <ShieldOff className="h-4 w-4" aria-hidden />
                                </Button>
                              ) : (
                                <Button
                                  variant="ghost"
                                  size="icon"
                                  className="h-8 w-8 text-success"
                                  onClick={() =>
                                    changeStatus.mutate({ id: certificate.id, status: "issued" })
                                  }
                                  aria-label={`Restore ${certificate.certificateNumber}`}
                                >
                                  <RotateCcw className="h-4 w-4" aria-hidden />
                                </Button>
                              )}
                              <Button
                                variant="ghost"
                                size="icon"
                                className="h-8 w-8 text-destructive"
                                onClick={() => setDeleteTarget(certificate)}
                                aria-label={`Delete ${certificate.certificateNumber}`}
                              >
                                <Trash2 className="h-4 w-4" aria-hidden />
                              </Button>
                            </div>
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              )}
            </CardContent>
          </Card>
        </>
      )}

      {/* QR dialog */}
      <Dialog open={Boolean(qrTarget)} onOpenChange={(open) => !open && setQrTarget(null)}>
        <DialogContent className="max-h-[92vh] max-w-[calc(100vw-1.5rem)] overflow-y-auto rounded-lg sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Certificate QR code</DialogTitle>
            <DialogDescription>
              Print this on the certificate. Scanning it opens the public verification page.
            </DialogDescription>
          </DialogHeader>

          {qrTarget && (
            <div className="space-y-4">
              <CertificateQrPreview
                value={buildVerificationUrl(qrTarget.verificationToken)}
                className="mx-auto h-56 w-56"
              />
              <div className="space-y-1 text-center">
                <p className="font-mono text-sm">{qrTarget.certificateNumber}</p>
                <p className="text-sm text-muted-foreground">{qrTarget.recipientName}</p>
                <p className="break-all text-xs text-muted-foreground">
                  {buildVerificationUrl(qrTarget.verificationToken)}
                </p>
              </div>
              <div className="flex flex-wrap justify-center gap-2">
                <Button
                  size="sm"
                  className="gap-2 bg-gradient-to-r from-primary to-secondary"
                  onClick={() =>
                    void downloadQrSvg(
                      buildVerificationUrl(qrTarget.verificationToken),
                      `qr-${qrTarget.certificateNumber}`
                    )
                  }
                >
                  <Download className="h-4 w-4" aria-hidden />
                  Download QR (SVG)
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  className="gap-2"
                  onClick={() => void copyLink(qrTarget)}
                >
                  <Copy className="h-4 w-4" aria-hidden />
                  Copy link
                </Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* Delete confirmation */}
      <AlertDialog
        open={Boolean(deleteTarget)}
        onOpenChange={(open) => !open && setDeleteTarget(null)}
      >
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete this certificate?</AlertDialogTitle>
            <AlertDialogDescription>
              {deleteTarget?.certificateNumber} for {deleteTarget?.recipientName} will be removed
              permanently, and its QR code will stop verifying. Revoking instead keeps the record
              and shows scanners that it is no longer valid.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
              onClick={() => deleteTarget && removeCertificate.mutate(deleteTarget.id)}
            >
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
